---
- name: setup navidrom w/ reverse proxy
  hosts: navidrome
  strategy: free
  gather_facts: yes  # yamllint disable-line rule:truthy
  become_method: sudo
  become: yes  # yamllint disable-line rule:truthy
  roles:
    - role: zfuller.navidrome_role
  vars:
    navidrome_domain: < domain >
    navidrome_caddyfile_loc: "{{ navidrome_config_dir }}/Caddyfile"
  tasks:
    - name: ensure user exists
      user:
        name: "{{ navidrome_user }}"
      register: navidrome_user_prop

    - name: ensure directories
      file:
        path: "{{ navidrome_user_prop.home }}"
        owner: "{{ navidrome_user }}"
        group: "{{ navidrome_group }}"
        state: directory
        mode: '0755'

    - name: add caddy repo
      apt_repository:
        repo: "deb [trusted=yes] https://apt.fury.io/caddy/ /"
        state: present

    - name: Install caddy webserver
      apt:
        name: caddy
        state: latest
        update_cache: yes  # yamllint disable-line rule:truthy
        force_apt_get: yes  # yamllint disable-line rule:truthy

    - name:
      file:
        path: "{{ navidrome_config_dir }}/access.{{ navidrome_domain }}.log"
        owner: "{{ navidrome_user }}"
        group: "{{ navidrome_group }}"
        mode: '0644'

    - name: push caddyfile
      copy:
        content: |
          {{ navidrome_domain }} {
            reverse_proxy localhost:{{ navidrome_port }}
            log {
                output file {{ navidrome_config_dir }}/access.{{ navidrome_domain }}.log {
                roll_size 1gb
                roll_keep 5
                roll_keep_for 24h
              }
            }
          }
        dest: "{{ navidrome_caddyfile_loc }}"
        owner: "{{ navidrome_user }}"
        group: "{{ navidrome_group }}"

    - name: push caddy systemd
      copy:
        content: |
          [Unit]
          Description=Caddy
          Documentation=https://caddyserver.com/docs/
          After=network.target

          [Service]
          User={{ navidrome_user }}
          Group={{ navidrome_group }}
          ExecStart=/usr/bin/caddy run --environ --config "{{ navidrome_caddyfile_loc }}"
          ExecReload=/usr/bin/caddy reload --config "{{ navidrome_caddyfile_loc }}"
          TimeoutStopSec=5s
          LimitNOFILE=1048576
          LimitNPROC=512
          PrivateTmp=true
          ProtectSystem=full
          AmbientCapabilities=CAP_NET_BIND_SERVICE

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/caddy.service
        owner: "{{ navidrome_user }}"
        group: "{{ navidrome_group }}"
    - name: reload systemd
      systemd:
        daemon_reload: yes  # yamllint disable-line rule:truthy

    - name: enable caddy
      systemd:
        name: caddy
        state: started
        enabled: yes  # yamllint disable-line rule:truthy
